stages:
  generate_data:
    cmd: python generate_iris.py
    outs:
    - data/iris.csv
  
  train:
    cmd: python train.py
    deps:
    - data/iris.csv
    - train.py
    outs:
    - data/processed/preprocessed.csv
    - model.pkl
